name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Format check
        shell: bash
        run: cargo fmt --all --check

      - name: Clippy (pedantic)
        shell: bash
        run: cargo clippy -- --no-deps -Dclippy::pedantic -Dwarnings

      - uses: taiki-e/install-action@cargo-hack

      - name: Test
        run: cargo hack --each-feature test --workspace

      - name: Run example
        run: cargo run --example visitor --features visitor
